// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhujhlzaytfoidgihlag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZodWpobHpheXRmb2lkZ2lobGFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MzkyNTAsImV4cCI6MjA2MzIxNTI1MH0.KUxsXqvLW9JGah_Q4GNAS27kIM_XNdxREEA7eCXLzJ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);